on:
  push:
    branches:
      - dev1

jobs:
  run_ssh_login:
    name: run_ssh_login
    runs-on: ubuntu-latest

    steps:
      - name: install ssh keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          
      - name: Deploy with rsync
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo 'connection enabled'" << 'EOF'
          whoami
          pwd
          ls -la
          EOF
